# ----------------------- F5-TAC Finetune Config ----------------------- #
exp_name: f5_tac_finetune

dataset_name: fisher_chunks_verysmall
data_root: /work/users/r/p/rphadke/JSALT/

tokenizer: custom
tokenizer_path: /work/users/r/p/rphadke/JSALT/fisher_chunks_verysmall/vocab.txt

pretrain: /work/users/r/p/rphadke/JSALT/ckpts/fisher_chunks_verysmall/pretrained_model_1250000.safetensors
finetune: true

learning_rate: 1e-7
epochs: 250

batch_size_per_gpu: 400
batch_size_type: frame
max_samples: 64
grad_accumulation_steps: 1
max_grad_norm: 1.0

save_per_updates: 5000
keep_last_n_checkpoints: 0
last_per_updates: 500

bnb_optimizer: false
log_samples: false

logger: wandb
