# ----------------------- F5-TAC Finetune Config ----------------------- #
exp_name: fisher_chunks_1K_LoRAv4.3

dataset_name: fisher_chunks_0.1K_v3.0
data_root: /work/users/r/p/rphadke/JSALT/

tokenizer: custom
tokenizer_path: /work/users/r/p/rphadke/JSALT/fisher_chunks_0.1K_v3.0/vocab.txt

pretrain: /work/users/r/p/rphadke/JSALT/ckpts/pretrained_model_1250000.safetensors
finetune: true

learning_rate: 1e-8
epochs: 50

batch_size_per_gpu: 3200
batch_size_type: frame
max_samples: 64
grad_accumulation_steps: 1
max_grad_norm: 1.0

save_per_updates: 1000
keep_last_n_checkpoints: 0
last_per_updates: 5000

bnb_optimizer: true
log_samples: false

logger: wandb
