# configs/finetuning_config.yaml
exp_name:                 F5TTS_v1_Base
data_root:                /work/users/r/p/rphadke/JSALT
dataset_name:             my_speak
finetune:                 true
logger:                   wandb
learning_rate:            5e-6
batch_size_per_gpu:       3200
batch_size_type:          frame
max_samples:              64
max_grad_norm:            1.0
epochs:                   100
num_warmup_updates:       20000
save_per_updates:         1000
keep_last_n_checkpoints:  0
last_per_updates:         5000
tokenizer:                custom
tokenizer_path:           /work/users/r/p/rphadke/JSALT/my_speak/vocab.txt